name:"my ci pipeline"
on:
  push:
    branches:
      - main
      - master
    pull_request:
        branches:
            - main
            - master
            
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
        - name: "on push"
            run: echo "push successful"

jobs:
on pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: "on pull request"
      run: echo "pull request successful"                   

            